name: Deploy all apps

on:
  push:
    branches:
      - main
    paths: apps/**

jobs:
  Apps-Deployment:
    if: "!contains(github.event.head_commit.message, '[SKIP-CI]')" 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - godfather
          - sportswear
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v2
      - name: Publish to APIM
        uses: Axway/presales-apim-cli-action@v0
        env:
          APIM_USER: ${{ secrets.APIM_USER }}
          APIM_PASS: ${{ secrets.APIM_PASS }}
          APIM_HOST: ${{ secrets.APIM_HOST }}
          APIM_PORT: ${{ secrets.APIM_PORT }}
        with:
          command: app import -c apps/${{ matrix.app }}/application-config.json